### ISSUE TITLE
GitHub version doesn't match PyPI

### ISSUE THREAD

**Issue by jeremyrgreen** [mjwen/geodesicLM#1]
The version of this package that pip installs seems to be newer than the code on GitHub.

**Comment by mjwen** [comment]
@jeremyrgreen thanks for catching this, updated to version in the GitHub repo.

**Comment by jeremyrgreen** [comment]
I wasn't referring to the version number, but the actual code. I believe GitHub matches version 1.0.2 in PyPI. Version 1.0.3 in PyPI has an interface closer to `scipy.optimize.least_squares`, returning an `OptimizeResult` object.
